Add Game Fetching Functionality and Implement Rate Limiting for Legion TD 2 API
paulfiesel/TD2-Stats pull request #22
Opened 2024-10-15 04:15 UTC by paulfiesel

Introduces functionality to fetch games from the Legion TD 2 API within a specified time range. It includes the following features:
- **Game Fetching**: Added a function to fetch games within a start and end time window, with results paginated.
- **Rate Limiting**: Integrated `pyrate-limiter` to respect the Legion TD 2 API rate limits (5 requests per second, 100 requests burst limit).
- **Environment Variables**: Utilized Python `dotenv` to manage the API key and other environment variables.

### Notes:
- The function currently returns an error: `Entry not found` (404 error). I believe this is due to the lack of game data for the requested timeframe(?)
- I still don’t fully understand all the nuances of how the API handles queries and responses yet, but I’ve added comments and I'll be reviewing the code again tomorrow.

2024-10-16 12:54 UTC, hansenreid requested changes
Left some comments for things that need to change. Also can you try making the calls with a large time duration or no time duration at all to ensure what you are doing is valid. I would assume that there is data in the last hour so a 404 surprises me.

2024-10-16 12:54 UTC, hansenreid commented on backend/games_api.py
> +burst_limiter = Limiter(InMemoryBucket([burst_rate]))
We should move this into a data class that contains all the configuration. On startup we can create a new instance of the class and provide it to any function that needs a value from it. See this blog on data classes: https://www.dataquest.io/blog/how-to-use-python-data-classes/

2024-10-16 12:54 UTC, hansenreid commented on backend/games_api.py
> +API_KEY = os.getenv("API_KEY")
We should handle the case where this is not set by throwing an exception

2024-10-16 12:54 UTC, hansenreid commented on backend/games_api.py
> +load_dotenv()
This should be moved to the configuration data class initiation logic.

2024-10-16 12:54 UTC, hansenreid commented on backend/games_api.py
> +        "limit": MAX_LIMIT  # Use the corrected limit of 50
We should explicitly set the offset to 0 for the first call

2024-10-16 12:54 UTC, hansenreid commented on backend/games_api.py
> +        burst_limiter.try_acquire("burst_api_call")
By default, these raise exceptions when we have exceeded the limits. We should wrap these in a try catch and add a delay to backoff until it is good to call again. 
- https://pyratelimiter.readthedocs.io/en/stable/#rate-limit-exceptions
- https://pyratelimiter.readthedocs.io/en/stable/#rate-limit-delays

2024-10-16 12:54 UTC, hansenreid commented on backend/games_api.py
> +        time.sleep(1)
We should not need this as the limiter should wait until it is safe to make a call again.

2024-10-16 12:54 UTC, hansenreid commented on backend/games_api.py
> +        more_pages = data.get('has_more', False)
Since you are not setting the offset for subsequent calls, if there are ever more than 50 pages returned this will loop infinitely.

2024-10-17 20:58 UTC, paulfiesel commented
I made all requested changes. However, when I test a day instead of an hour, I get the same message:

Updated code:
```
# Function to get games from the last day
def get_last_day_games():
    end_time = datetime.now(timezone.utc)
    start_time = end_time - timedelta(days=1)

    games = fetch_games(start_time, end_time)
    print(f"Retrieved {len(games)} games from the last day.")
    return games

# Call on startup
if __name__ == "__main__":
    get_last_day_games()
```

Error 404:
```
(venv) paulfiesel@Paul-PUGET2:/mnt/c/Sync/Dev Projects/TD2-Stats/backend$ python games_api.py
Error: 404, {"err":"Entry not found."}
Retrieved 0 games from the last day.
```

2024-10-17 22:27 UTC, hansenreid approved these changes
Ship it!

2024-10-17 22:28 UTC, merged